EXAMS = {
    "finra-sie": "FINRA SIE: Securities Industry Essentials Examination",
    "finra-s6": "FINRA Series 6: Investment Company and Variable Contracts Products Representative Examination",
    "finra-s7": "FINRA Series 7: General Securities Representative Examination",
    "finra-s22": "FINRA Series 22: Direct Participation Programs Limited Representative Examination",
    "finra-s57": "FINRA Series 57: Securities Trader Representative Examination",
    "finra-s79": "FINRA Series 79: Investment Banking Representative Examination",
    "finra-s82": "FINRA Series 82: Private Securities Offerings Representative Examination",
    "finra-s86": "FINRA Series 86/87: Research Analyst Examination",
    "finra-s99": "FINRA Series 99 - Operations Professional Examination",
    "finra-s4": "FINRA Series 4: Registered Options Principal Examination",
    "finra-s9": "FINRA Series 9/10: General Securities Sales Supervisor Examination",
    "finra-s14": "FINRA Series 14: Compliance Officer Examination",
    "finra-s16": "FINRA Series 16: Supervisory Analysts Examination",
    "finra-s23": "FINRA Series 23: General Securities Principal - Sales Supervisor Module Examination",
    "finra-s24": "FINRA Series 24: General Securities Principal Examination",
    "finra-s26": "FINRA Series 26: Investment Company Products/Variable Contracts Limited Principal Examination",
    "finra-s27": "FINRA Series 27: Financial and Operations Principal Examination",
    "finra-s28": "FINRA Series 28: Introducing Broker/Dealer Financial and Operations Principal Examination",
    "finra-s39": "FINRA Series 39: Direct Participation Programs Limited Principal Examination",
    "finra-s50": "FINRA Series 50: Municipal Advisor Representative Examination",
    "finra-s51": "FINRA Series 51: Municipal Fund Securities Limited Principal Examination",
    "finra-s52": "FINRA Series 52: Municipal Securities Representative Examination",
    "finra-s53": "FINRA Series 53: Municipal Securities Principal Examination",
    "finra-s54": "FINRA Series 54: Municipal Advisor Principal Examination",
    "finra-s3": "FINRA Series 3: National Commodities Futures Examination",
    "finra-s30": "FINRA Series 30: NFA Branch Manager Examination (Formerly, Branch Managers Examination: Futures)",
    "finra-s31": "FINRA Series 31: Futures Managed Funds Examination",
    "finra-s32": "FINRA Series 32: Limited Futures Examination - Regulations",
    "finra-s34": "FINRA Series 34: Retail Off-Exchange Forex Examination",
    "finra-s63": "FINRA Series 63: Uniform Securities Agent State Law Examination",
    "finra-s65": "FINRA Series 65: Uniform Investment Adviser Law Examination",
    "finra-s66": "FINRA Series 66: Uniform Combined State Law Examination",
    # "insurance-ca-adjuster-independent": "California Department of Insurance - Insurance Adjuster (Independent) Examination",
    # "insurance-ca-adjuster-public": "California Department of Insurance - Public Insurance Adjuster",
    # "insurance-ca-agent-accident": "California Department of Insurance - Accident and Health or Sickness Agent Examination",
    # "insurance-ca-agent-accident-spanish": "California Department of Insurance - Accident and Health or Sickness Agent Examination",
    # "insurance-ca-agent-casualty": "California Department of Insurance - Casualty Examination",
    # "insurance-ca-agent-commercial": "California Department of Insurance - Commercial Insurance Examination",
    # "insurance-ca-agent-life-disability": "California Department of Insurance - Life and Disability Analyst Examination",
    # "insurance-ca-agent-life-funeral": "California Department of Insurance - Life-Limited to the Payment of Funeral and Burial Expenses Examination",
    # "insurance-ca-agent-life-funeral-spanish": "California Department of Insurance - Life-Limited to the Payment of Funeral and Burial Expenses Examination (Spanish Language)",
    # "insurance-ca-agent-life": "California Department of Insurance - Life Agent Examination",
    # "insurance-ca-agent-life-spanish": "California Department of Insurance - Life Agent Examination (Spanish Language)",
    # "insurance-ca-agent-auto": "California Department of Insurance - Limited-Lines Automobile Agent Examination",
    # "insurance-ca-agent-personal-lines": "California Department of Insurance - Personal Lines Examination",
    # "insurance-ca-agent-property": "California Department of Insurance - Property Examination",
}
